### ISSUE TITLE
Add individual requirements ranking to spreadsheet(Maria)

### ISSUE THREAD

**Issue by BhanuTeja-007** [Unmesha-SE/smarter-university-system#102]
Recording the individual prioritization of requirements in a spreadsheet for documentation and analysis.

This activity relates to Epic #7

**Comment by Unmesha-SE** [comment]
@maria-vilanova , i took a look at your priorities and it looks correct

**Comment by maria-vilanova** [comment]
> @maria-vilanova , i took a look at your priorities and it looks correct

Thank you!

**Comment by maria-vilanova** [comment]
This is my requirements order by priority:
27, 28, 22, 33, 32, 26, 34, 35, 21, 20, 13, 29, 14, 16, 1, 12, 25, 18, 19, 2, 11, 15, 7, 8, 5, 6, 4, 31, 30, 3, 9, 24, 23, 37, 36, 10, 17
