### ISSUE TITLE
Generate input values for 'text' and 'directed' parameters

### ISSUE THREAD

**Issue by Udit2399** [Unmesha-SE/smarter-university-system#110]
This activity involves determining the parameter values for a valid/nominal API usage.

This activity belongs to epic #8

**Comment by maria-vilanova** [comment]
Modifying this activity to reflect what we actually have to do (and have completed). We distributed and assigned the input generation work among the team, and for each parameter identified input values using equivalence partitions, boundary value analysis, and variable interactions.

This activity now relates to identifying input values for the 'text' and 'directed' parameters, which was assigned to me. I have documented my analysis here: 
[Task 5.docx](https://github.com/Unmesha-SE/smarter-university-system/files/13454348/Task.5.docx)
