### ISSUE TITLE
Document 'recipients' and 'post_time' test cases in spreadsheet

### ISSUE THREAD

**Issue by Udit2399** [Unmesha-SE/smarter-university-system#115]
This activity involves documenting the test cases for slightly deviated API usage, after reviewing the test cases.

This activity belongs to epic #8

**Comment by maria-vilanova** [comment]
Modifying this activity to reflect what we're actually doing.

This activity now relates to documenting the input test cases generated for the 'recipients' and 'post_time' parameters into the Task 5 spreadsheet.

**Comment by Unmesha-SE** [comment]
Methods Equivalence partition, boundary value analysis, variable interactions have been used to come up with appropriate values for the parameter
