### ISSUE TITLE
Document 'text' and 'directed' test cases in spreadsheet

### ISSUE THREAD

**Issue by Udit2399** [Unmesha-SE/smarter-university-system#116]
This activity involves documenting the test cases for invalid API usage, after reviewing the test cases.

This activity belongs to epic #8

**Comment by maria-vilanova** [comment]
Modifying this activity to reflect what we're actually doing.

This activity now relates to documenting the input test cases generated for the 'text' and 'directed' parameters into the Task 5 spreadsheet.
