### ISSUE TITLE
Identify requirements epics (Bhanu)

### ISSUE THREAD

**Issue by Naga-Chinta** [Unmesha-SE/smarter-university-system#63]
This activity is related to identifying all the required epics to deliver the features and functionality that customer needs. This is an important step in creating user stories.
This activity belongs to epic #6

**Comment by BhanuTeja-007** [comment]
Requirements Epics:

1. Course Management:
    - User Story 1: As an administrator, I want to manage class enrollments, including maximum capacities, adding/removing students, and monitoring enrollment percentages.
    - User Story 2: As a student, I want to view available classes, check their details (identifier, title, lecturer, syllabus), and sign up for classes that I haven't attended before.

2. Class Information and Communication:
    - User Story 3: As a student, I want to access class-specific information, including lecture schedules, topics, and instructor details for the courses I've enrolled in.
    - User Story 4: As an instructor, I want to maintain a syllabus page with lecture dates, topics, and the ability to update information during the semester.

3. Enrollment and Prerequisites:
    - User Story 5: As a student, I want to request enrollment in a course for which I don't meet prerequisites, and await confirmation from both administrator and instructor to enroll.
    - User Story 6: As an administrator/instructor, I want to receive enrollment requests for classes and approve/reject them accordingly.

4. Instructor and Student Interaction:
    - User Story 7: As an instructor, I want to access information about enrolled students (names, IDs) in my classes.
    - User Story 8: As an instructor/teaching assistant, I want to assign students into groups for team assignments and view the team composition for specific classes.

5. Grading System:
    - User Story 9: As an instructor/teaching assistant, I want to enter grades for exams, assignments, and quizzes individually or in bulk.
    - User Story 10: As an instructor/teaching assistant/student, I want to view grades (averages, highest, lowest) for assignments and exams throughout the semester.
