### ISSUE TITLE
Identify requirements epics (Maria)

### ISSUE THREAD

**Issue by Naga-Chinta** [Unmesha-SE/smarter-university-system#64]
This activity is related to identifying all the required epics to deliver the features and functionality that customer needs. This is an important step in creating user stories.
This activity belongs to epic #6

**Comment by maria-vilanova** [comment]
Epic ideas:

Option 1: divide requirements based on Roles
- Student Epic
- Instructor Epic
- TA Epic
- Administrator Epic

Option 2: divide requirements into high-level 'functional' categories
- Course enrollment management
   -> includes Student course enrollment (for students) and Enrollment requests (for students, admins and instructors)
- Student course management
   -> includes Course attendance, Course grading, and Course group work (for students)
- Instructor course management
   -> includes Course grading, Course syllabus management, Course group work, and general course management (for instructors and TAs)
- Information visualization
   -> includes Course information (for students and instructors) and Instructor information (for administrators)
- Account management (?)

Option 3: break down the functional categories a bit more
- Student course enrollment
- Enrollment requests
- Course grading
- Course syllabus management
- Course group assignments/work
- Course information visualization
- Instructor information visualization
- Course attendance or management (?)
- Account management (?)

**Comment by maria-vilanova** [comment]
[SOW Analysis.txt](https://github.com/Unmesha-SE/smarter-university-system/files/13314123/SOW.Analysis.txt)

Here is the rest of my analysis/brainstorm so far. It includes identified roles and potential actions/tasks to use for user stories.

Note: The potential actions that I'm unsure of are marked with a (?). Also, some of the potential actions I identified are inferred, not explicit in the document. I'm thinking of creating a brainstorm spreadsheet to better explain my thoughts.

**Comment by Unmesha-SE** [comment]
Hi Maria,
The epics look pretty good and so does the user stories. I have considered the epics in very broad functional categories and wrote detailed user stories. Please take a look at my activity and then all of us in the team can have a brainstorm together.

**Comment by maria-vilanova** [comment]
Hi Unmesha,
Thanks for the feedback! I've just posted my more 'formalized' user stories ideas in my activity #72 . It's still in work but please feel free to take a look at them and let me know what you think.
