### ISSUE TITLE
Identify requirements epics (Udit)

### ISSUE THREAD

**Issue by Naga-Chinta** [Unmesha-SE/smarter-university-system#65]
This activity is related to identifying all the required epics to deliver the features and functionality that customer needs. This is an important step in creating user stories.
This activity belongs to epic #6

**Comment by Udit2399** [comment]
The requirement epics can be divided into 4 main roles:

- Instructor
- Teaching assistant
- Student
- Admin

The above user roles, constitute the following broad level functionality epics:

- Course management
- Enrollment management
- User management
