### ISSUE TITLE
Organize SOW statements under epics (Maria)

### ISSUE THREAD

**Issue by Naga-Chinta** [Unmesha-SE/smarter-university-system#68]
This activity is mainly related to organizing the statement of work with their respective epics, so as to ensure that the team is developing user stories aligned with the SOW.
This activity belongs to epic #6

**Comment by maria-vilanova** [comment]
I've put together a spreadsheet with my identified SOW statements organized under my identified epics. You can find it here: 
[User stories.xlsx](https://github.com/Unmesha-SE/smarter-university-system/files/13344910/User.stories.xlsx)

Please refer to Sheet 1 (SOW Analysis) specifically. It is still in work but you can see my thought process and ideas in there.
