### ISSUE TITLE
Write user stories from SOW statements (Maria)

### ISSUE THREAD

**Issue by Naga-Chinta** [Unmesha-SE/smarter-university-system#72]
This activity revolves around writing user stories from SOW, this is an important step in the process of software development. The team can ensure that all the required functionalities and features are delivered by writing user stories from SOW.
This activity belongs to epic #6

**Comment by maria-vilanova** [comment]
I've put together a spreadsheet with my SOW analysis and my identified user stories. You can find it here: 
[User stories.xlsx](https://github.com/Unmesha-SE/smarter-university-system/files/13344922/User.stories.xlsx)

Please refer to Sheet 2 (User stories) specifically.
