### ISSUE TITLE
Write user stories from SOW statements (Bhanu)

### ISSUE THREAD

**Issue by Naga-Chinta** [Unmesha-SE/smarter-university-system#74]
This activity revolves around writing user stories from SOW, this is an important step in the process of software development. The team can ensure that all the required functionalities and features are delivered by writing user stories from SOW.
This activity belongs to epic #6

**Comment by BhanuTeja-007** [comment]
User Stories:

1. Course Management:
    - As an administrator, I should be able to add or remove students from classes.
    - As an administrator, I should receive notifications when a course is 80% full.

2. Class Information and Communication:
    - As a student, I should be able to view all available classes upon logging in.
    - As a student, I should access a class's identifier, title, lecturer, and syllabus details with dates and topics.

3. Enrollment and Prerequisites:
    - As a student, I should be able to request enrollment in a course for which I don't meet prerequisites.
    - As an administrator/instructor, I should receive enrollment requests and confirm student enrollments.

4. Instructor and Student Interaction:
    - As an instructor, I should access a list of enrolled students for each class I'm teaching.
    - As an instructor/teaching assistant, I should be able to assign students into groups for team assignments.

5. Grading System:
    - As an instructor/teaching assistant, I should enter grades for exams, assignments, and quizzes.
    - As a student/instructor, I should view grades for assignments and exams.
