### ISSUE TITLE
Initial review/study of the activity post API endpoints (Maria)

### ISSUE THREAD

**Issue by Udit2399** [Unmesha-SE/smarter-university-system#81]
This activity is a crucial initial step which involves studying the possible bad requests to the system via the API endpoints. This activity will involve analyzing the possible violations to the system boundaries via API calls and defining the boundary conditions for the system to shield itself from the bad API calls.

This activity belongs to the epic #8

**Comment by maria-vilanova** [comment]
This document contains my analysis and input generation ideas for my assigned parameters (text and directed).
Please let me know your thoughts/comments.

[Task 5.docx](https://github.com/Unmesha-SE/smarter-university-system/files/13433399/Task.5.docx)

**Comment by Unmesha-SE** [comment]
This looks good to me.
