### ISSUE TITLE
Initial review/study of the activity post API endpoints (Naga)

### ISSUE THREAD

**Issue by Udit2399** [Unmesha-SE/smarter-university-system#82]
This activity is a crucial initial step which involves studying the possible bad requests to the system via the API endpoints. This activity will involve analyzing the possible violations to the system boundaries via API calls and defining the boundary conditions for the system to shield itself from the bad API calls.

This activity belongs to the epic #8

**Comment by Naga-Chinta** [comment]
Scenario 1: Missing parameters
Do not include one or more required parameters in the request.
Submit a request with one or more parameters set to an empty value.

Scenario 2: Invalid parameter values
Submit a request with a text message that is longer than the specified length limit.
Submit a request with the "directed" parameter set to TRUE, but omit the "recipients" parameter.
Submit a request with an invalid user ID in the "recipients" parameter.
Submit a request with an invalid date and time format for the "post_time" or "due_time" parameters.
Submit a request with the "flag" parameter set to an invalid value.
Submit a request with a latitude or longitude value that is outside the valid range.

Scenario 3: Unexpected interactions between parameters
Submit a request with the "directed" parameter set to TRUE, and also include a value for the "post_time" parameter.
Submit a request with the "due_time" parameter set to a date and time that is earlier than the "post_time" parameter.

Scenario 4: Malicious input
Submit a request with HTML tags or other potentially harmful code in the text message.
Submit a request with an attempt to inject malicious code into the request parameters.

Scenario 5: Handling Excessive Data
Evaluate the API's behavior when presented with a text message that exceeds the specified length limit by a significant margin.
Assess the API's ability to handle high-volume traffic by sending multiple requests in quick succession.

Scenario 6: Managing Unexpected Data Formats
Verify the API's error handling mechanism when input values are provided in data types that differ from the specified requirements.
Evaluate the API's ability to parse and interpret date and time values that deviate from the specified ISO 8601 format.

Scenario 7: Enforcing Access Control and Authorization
Challenge the API with unauthorized credentials or requests lacking the necessary permissions to access the endpoint.
Attempt to modify or delete activity posts owned by other users without the appropriate access privileges.

Scenario 8: Addressing Database-Related Issues
Simulate scenarios that could trigger database errors, such as creating a post with an existing ID or referencing non-existent user IDs.
Test the API's resilience to database unavailability or connectivity disruptions.

Scenario 9: Ensuring Integration with External Systems
Evaluate the API's handling of communication failures or inconsistencies in data exchange with other external systems.
Verify the API's ability to accurately process and respond to events or updates originating from other systems.

Scenario 10: Validating Boundary Conditions and Edge Cases
Test the API's behavior when input values approach the specified boundaries, such as the maximum length of a text message or the valid range for latitude and longitude values.
Explore scenarios involving extreme or unusual values, such as dates in the distant future or past, or exceptionally large or small numbers.

By subjecting the API to a wide range of testing scenarios, encompassing valid, invalid, and malicious inputs, you can contribute to its robustness and security.

**Comment by Unmesha-SE** [comment]
This seems pretty good and covers all the scenarios. I uploaded the required criteria in our shared google drive. Have a look.
