### ISSUE TITLE
Create and add independent binary tree graphs in GraphViz(Unmesha)

### ISSUE THREAD

**Issue by BhanuTeja-007** [Unmesha-SE/smarter-university-system#86]
This activity prioritizes the systematic process of requirements prioritization within the team. It involves individual ranking using the binary tree method, collaborative documentation in a Graphviz document and a requirements spreadsheet, iterative reviews, team priority alignment, and effective project management. The goal is to ensure that the team collectively defines and prioritizes requirements to guide project success.

This activity relates to Epic #7

**Comment by Unmesha-SE** [comment]
The binary tree was created using Graphviz online
![Binary Tree Graphviz](https://github.com/Unmesha-SE/smarter-university-system/assets/144734191/9c65fabf-1b28-4cdf-89ce-238657be3e08)
