### ISSUE TITLE
Create and add independent binary tree graphs in GraphViz(Maria)

### ISSUE THREAD

**Issue by BhanuTeja-007** [Unmesha-SE/smarter-university-system#87]
This activity prioritizes the systematic process of requirements prioritization within the team. It involves individual ranking using the binary tree method, collaborative documentation in a Graphviz document and a requirements spreadsheet, iterative reviews, team priority alignment, and effective project management. The goal is to ensure that the team collectively defines and prioritizes requirements to guide project success.

This activity relates to Epic #7

**Comment by maria-vilanova** [comment]
This is my binary tree graph.

digraph maria_vilanova {
1 -> 2
1 -> 13
2 -> 3
2 -> 12
3 -> 9
3 -> 4
4 -> 30
4 -> 5
5 -> 6
5 -> 7
7 -> 8
7 -> 11
9 -> 10
9 -> R9
10 -> 17
10 -> 23
11 -> 15
11 -> R11
12 -> 18
12 -> R12
13 -> 14
13 -> 20
14 -> 16
14 -> 29
18 -> 19
18 -> 25
20 -> L20
20 -> 21
21 -> L21
21 -> 22
22 -> 26
22 -> 27
23 -> 36
23 -> 24
26 -> 34
26 -> 33
33 -> 32
33 -> R33
27 -> 28
27 -> R27
30 -> L30
30 -> 31
34 -> 35
34 -> R34
36 -> L36
36 -> 37
}

![graphviz](https://github.com/Unmesha-SE/smarter-university-system/assets/143459552/07ed4301-7fe3-404c-9c50-704d69a07c36)
