### ISSUE TITLE
Prioritize and rank user stories independently(Unmesha)

### ISSUE THREAD

**Issue by BhanuTeja-007** [Unmesha-SE/smarter-university-system#91]
Team members individually assess and prioritize user stories based on their importance. This approach allows for diverse perspectives and ensures a well-rounded evaluation of each user story's significance.

This activity relates to Epic #7

**Comment by Unmesha-SE** [comment]
Based on the combined user stories, prioritization and ranks were allotted to them based on the binary tree traversal
