### ISSUE TITLE
Combine and rank team requirements priorities

### ISSUE THREAD

**Issue by BhanuTeja-007** [Unmesha-SE/smarter-university-system#96]
Merging individual priorities and determining a unified ranking for team-wide requirements.

This activity relates to Epic #7

**Comment by maria-vilanova** [comment]
This is the combined/overall requirement order by priority:
27, 28, 26, 33, 34, 35, 22, 21, 30, 32, 29, 19, 20, 17, 13, 14, 25, 16, 1, 2, 6, 8, 31, 9, 5, 7, 12, 11, 18, 15, 10, 4, 3, 24, 37, 36, 23
